### PR TITLE
Correctly ignore fields using ObjectTypeExtension

### LINKED ISSUE #3776: Ignoring fields with `ObjectTypeExtension<T>` does not work
**Describe the bug**
Calling `Ignore` on the `descriptor` of a `ObjectTypeExtension<T>` does not work. The supposedly ignored field is still part of the generated schema.

**To Reproduce**
```csharp
public class Example
{
    public string Property1 { get; set; }
    public string Property2 { get; set; }
}

public class ExampleType : ObjectType<Example> { }

public class ExampleTypeExtensions : ObjectTypeExtension<Example>
{
    protected override void Configure(IObjectTypeDescriptor<Example> descriptor)
    {
        descriptor.Name(nameof(Example));

        // this is the problematic portion
        descriptor.Ignore(f => f.Property2);
    }
}

public class Query
{
    public Example? GetExample() => null;
}

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services
            .AddGraphQLServer()
            .AddTypeExtension<ExampleTypeExtensions>()
            .AddQueryType<Query>();
    }
}
```

Leads to:

```graphql
type Example {
  property1: String!
  property2: String!
}
```

**Expected behavior**
`Property2` should not be part of the generated schema:

```graphql
type Example {
  property1: String!
}
```

**Desktop (please complete the following information):**
- Version: `11.3.0-preview.7`

### PR DESCRIPTION
**Pull request by tobias-tengler**
Closes #3776

### CODE REVIEW

**Comment by tobias-tengler** [comment]
@michaelstaib Do you see a better way on how to solve the issue at hand? It feels weird that I have to instantiate a `ObjectFieldBinding` by hand.

File: src/HotChocolate/Core/src/Types/Types/Descriptors/ObjectTypeDescriptor.cs [hunk 1]
```diff
@@ -69,6 +69,19 @@ protected ObjectTypeDescriptor(IDescriptorContext context)
...
 
+            foreach (ObjectFieldDescriptor field in Fields)
+            {
+                if (!field.Definition.Ignore)
+                    continue;
+
+                // if this definition is used for a type extension we need a 
+                // binding to a field which shall be ignored. In case this is a 
+                // definition for the type it will be ignored by the type initialization.
+                Definition.FieldIgnores.Add(new ObjectFieldBinding(
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Types/Types/Descriptors/ObjectTypeDescriptor.cs:80]: I have added a note why we have this binding here so that in case of a refactoring we know why this is done.

**Review by michaelstaib — APPROVED** [review]

File: src/HotChocolate/Core/src/Types/Types/Descriptors/ObjectTypeDescriptor.cs [hunk 2]
```diff
@@ -69,6 +69,21 @@ protected ObjectTypeDescriptor(IDescriptorContext context)
                 Definition.AttributesAreApplied = true;
             }
 
+            foreach (ObjectFieldDescriptor field in Fields)
+            {
+                if (!field.Definition.Ignore)
+                {
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Types/Types/Descriptors/ObjectTypeDescriptor.cs:75]: I fixed the code style here, we always write the braces in C# code in order better see that

```csharp
if(foo is true)
    dosomething();
    dosomething();   
```

is really

```csharp
if(foo is true)
{
    dosomething();
}

dosomething();   
```

This issue quickly happens on refactorings and we decided to just enforce braces for if clauses.
