### PR TITLE
Fix race condition on MethodInfo.GetParameters()

### LINKED ISSUE #8433: [Regression] Multi-threaded access to discover types throws "The given key was not present in the dictionary" exception
### Product

Hot Chocolate

### Version

15.1.4

### Steps to reproduce

When upgrading from HotChocolate v15.1.3 to v15.1.4 we started encountering an issue with our integration tests.

To give you a bit background, we use `WebApplicationFactory` with parallel test execution.

After upgrading to v15.1.4 whenever the tests are run in parallel, random tests fail with the same error message in the log below, but with random different fields (sometimes for the same test).

I wonder if this is some sort of a race condition or locking that's changed which is causing multiple threads to access the same dictionary during setup.

Apologies for not providing a re-production, but it's a hard scenario to re-produce, I was hoping you might have some ideas based on the changes that went between those 2 versions.

Can you please advise.

Thanks.

### What is expected?

For the tests to run without HotChocolate erroring out.

### What is actually happening?

HotChocolate is erroring out.

### Relevant log output

```shell
Message: 
  HotChocolate.SchemaException : For more details look at the `Errors` property.
  
  1. The given key 'System.String id' was not present in the dictionary. (Beacon.API.Assets.GraphQL.QueryType)
  

Stack Trace: 
  TypeInitializer.DiscoverTypes()
  TypeInitializer.Initialize()
  Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
  Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
  SchemaBuilder.Create(IDescriptorContext context)
  ISchemaBuilder.Create(IDescriptorContext context)
  RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
  RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
  RequestExecutorResolver.CreateRequestExecutorAsync(String schemaName, Boolean isInitialCreation, CancellationToken cancellationToken)
  RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)  RequestExecutorResolver.WarmupAsync.__WarmupSchemaAsync|40_0(string schemaName, System.Threading.CancellationToken cancellationToken)	Unknown
  RequestExecutorResolver.WarmupAsync(System.Threading.CancellationToken cancellationToken)	Unknown
  RequestExecutorWarmupService.StartAsync(System.Threading.CancellationToken cancellationToken)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tobias-tengler**
Fixes #8433

`RuntimeMethodInfo.GetParameters` is [not thread-safe](https://source.dot.net/#System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs,f1e3caae285df850,references), but we request parameters in a variety of places during type initialization. Because of this we could end up with two different `ParameterInfo` instances for the same parameter, which leads to the missing dictionary key error reported in the linked issue.

This PR addresses this issue by adding a new thread-safe `ITypeInspector.GetParameters()` that also caches the parameter instances, similar to `GetMembers`.
After Feedback from Michael I also added a `ParameterInfoComparer` that ensures that this also works if we ever decide to make the `ExtendedMethodInfo` public and there's a race condition between us and the developer calling `GetParameters`.

### CODE REVIEW

**Comment by michaelstaib** [comment]
Actually, this is not the fix :D 

This would just make the window smaller.

**Review by michaelstaib — APPROVED** [review]

File: src/HotChocolate/Core/src/Types/Types/Descriptors/Conventions/DescriptorContext.cs [hunk 1]
```diff
@@ -42,13 +40,16 @@ private DescriptorContext(
...
         TypeInterceptor = typeInterceptor;
-        ResolverCompiler = new DefaultResolverCompiler(
-            schemaServices,
-            _serviceHelper.GetParameterExpressionBuilders());
 
         TypeConverter = _serviceHelper.GetTypeConverter();
         InputFormatter = _serviceHelper.GetInputFormatter(TypeConverter);
         InputParser = _serviceHelper.GetInputParser(TypeConverter);
+
+        TypeInspector = this.GetConventionOrDefault<ITypeInspector>(new DefaultTypeInspector());
```
Comment (atykhyy) [inline src/HotChocolate/Core/src/Types/Types/Descriptors/Conventions/DescriptorContext.cs:48]: This change made it so that `IRequestExecutorBuilder.ConfigureSchema()` can no longer override the default type inspector, as delegates added via `ConfigureSchema()` are invoked after the `DescriptorContext` is created and thus any `ISchemaBuilder.AddConvention<ITypeInspector>(...)` have no effect. I had to dig up something called `IRequestExecutorOptionsProvider` to override the default type inspector.

Comment (tobias-tengler) [reply src/HotChocolate/Core/src/Types/Types/Descriptors/Conventions/DescriptorContext.cs:48]: I believe we also removed `IRequestExecutorOptionsProvider` for v16. Can you open an issue for this and detail why you need a custom TypeInspector?

Comment (atykhyy) [reply src/HotChocolate/Core/src/Types/Types/Descriptors/Conventions/DescriptorContext.cs:48]: Oh boy... There are multiple reasons, not all of which may be valid at this point/in the upcoming v16, as I do not follow HC development closely. I'd have to invest some time in trying to upgrade my environment to v16 and see if I still need that and what for. Basically I have to adapt HC to consume a pre-existing customer type/attribute schema which I cannot modify/decorate with HC attributes. Adaptations I had to do so far include inserting type converters and changing member types to conceal from HC types it cannot or should not handle, renaming and hiding members (including enums, where IIRC HC exposes original enum value names in the schema even if one renames them via the naming convention), and fixing random bugs such as HC execution stack barfing on default `ImmutableArray` values.

Comment (tobias-tengler) [reply src/HotChocolate/Core/src/Types/Types/Descriptors/Conventions/DescriptorContext.cs:48]: Any reason why you're not reaching for the HC's fluent API to just wrap / exclude the existing types you can't annotate with attributes?

Comment (atykhyy) [reply src/HotChocolate/Core/src/Types/Types/Descriptors/Conventions/DescriptorContext.cs:48]: My adapter component has to discover customer types and attributes at runtime. I do create `ObjectType<>`'s for compound types and so on, so in that sense I use HC fluent APIs, but I found I could not do all I needed with them. I might be able to use dynamic schemas (`ITypeModule`) to generate a schema from scratch without involving `ITypeInspector` mechanics at all, though that would mean a complete rewrite of my adapter component. However, it's grown to be such a mess of workarounds that that might be the wiser approach.
