### PR TITLE
Fixed issue where the PagingHelper introduced a self-reference which cause type system initialization issues.

### LINKED ISSUE #2883: OffsetPaging. The compilation is unable to resolve cyclic dependencies
We are in the process of moving our preproduction services to v11. And we're facing a really big issue which is a blocker for us.

Suppose, we have a collection of Users but each user has its own collection of users, say 'Parents'. It's enough to get the compilation failed. 
@michaelstaib this is a really critical issue so I kindly ask you to give enough priority to that issue to fix it ASAP. I've made a complete test reproducing that error.

```
public class Issue2883Reproducing
    {
        private readonly ITestOutputHelper _testOutputHelper;

        public class User
        {
            public string? FirstName { get; set; }

            public List<User> Parents { get; set; }
        }

        public class UserType : ObjectType<User>
        {
            protected override void Configure(IObjectTypeDescriptor<User> descriptor)
            {
                descriptor.Field(i => i.Parents).UseOffsetPaging<UserType>().Resolve((_1, _2) => new[] { new User { FirstName = "Mother" }, new User { FirstName = "Father" } });
            }
        }

        public class Query
        {
            public List<User> Users => new()
            {
                new User()
            };
        }

        public class QueryType : ObjectType<Query>
        {
            protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
            {
                descriptor.Field(t => t.Users)
                    .UseOffsetPaging<UserType>();
            }
        }

        public Issue2883Reproducing(ITestOutputHelper testOutputHelper)
        {
            _testOutputHelper = testOutputHelper;
        }

        [Fact]
        public async Task Test()
        {
            IRequestExecutor executor =
                await new ServiceCollection()
                    .AddGraphQL()
                    .AddQueryType<QueryType>()
                    .SetPagingOptions(new PagingOptions { DefaultPageSize = 50 })
                    .Services
                    .BuildServiceProvider()
                    .GetRequestExecutorAsync();

            IExecutionResult executionResult = await executor
                .ExecuteAsync(@"
                {
                    users {
                        items
                        {
                            parents
                            {
                                items
                                {
                                    firstName
                                }
                            }
                       }
                    }
                }");

            foreach (IError error in executionResult.Errors ?? new IError[0])
                _testOutputHelper.WriteLine(error.Message);

            Assert.Equal(0, executionResult.Errors?.Count ?? 0);
        }
    }
```

### PR DESCRIPTION
**Pull request by PascalSenn**
By resolving all self referencing types, we can try to fix the cyclic dependency problem. it can lead to other problems though. 

Closes #2883

### CODE REVIEW

File: src/HotChocolate/Core/src/Types/Configuration/TypeInitializer.cs [hunk 1]
```diff
@@ -541,6 +556,29 @@ bool CompleteType(RegisteredType registeredType)
...
+                    .Select(x => x.TypeReference)
+                    .OfType<ExtendedTypeReference>()
+                    .Select(x => x.Type);
+
+                IEnumerable<IExtendedType> references = type.References
+                    .OfType<ExtendedTypeReference>()
+                    .Select(x => x.Type);
+
+                if (dependencies.Intersect(references).Any())
+                {
```
Comment (PascalSenn) [inline src/HotChocolate/Core/src/Types/Configuration/TypeInitializer.cs:576]: This could also initialize other dependencies that should not yet be resovler
we may want to do a deep check here to see if the missing dependencies really form a cycle.

Comment (michaelstaib) [reply src/HotChocolate/Core/src/Types/Configuration/TypeInitializer.cs:576]: I think we should also have a look at why the dependencies are hard dependencies.

Meaning in the offset case we have 

ConnectionA->EdgeA->TypeA->ConnectionB->EdgeB->TypeB->ConnectionA

each of the dependency demands completion. We also have a concept of weak dependencies. So what actually should happen is that field dependencies are weak dependencies... meaning the pointer from TypeA to ConnectionB should be weak.

File: src/HotChocolate/Core/src/Types/Types/Pagination/PagingHelper.cs [hunk 2]
```diff
@@ -33,25 +33,25 @@ public static class PagingHelper
...
-
-                    var configuration = new TypeConfiguration<ObjectFieldDefinition>
-                    {
-                        Definition = d,
-                        On = ApplyConfigurationOn.Completion,
-                        Configure = (c, d) => ApplyConfiguration(
-                            c, d, entityType, resolvePagingProvider, options, placeholder)
-                    };
-
-                    configuration.Dependencies.Add(
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Types/Types/Pagination/PagingHelper.cs:49]: This actually is correct sine we need the entity type to be named first. The issue as I pointed is that the field dependency is demanding completion.

File: src/HotChocolate/Core/src/Types/Types/Descriptors/Definitions/TypeDependencyKind.cs [hunk 3]
```diff
@@ -6,7 +6,7 @@ namespace HotChocolate.Types.Descriptors.Definitions
     public enum TypeDependencyKind
     {
         /// <summary>
-        /// The dependency instance does not be completed.
+        /// The dependency instance does not need to be completed.
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Types/Types/Descriptors/Definitions/TypeDependencyKind.cs:9]: We need better documentation on this.

File: src/HotChocolate/Core/src/Types/Types/Pagination/PagingHelper.cs (hunk 2 above)
Comment (michaelstaib) [reply src/HotChocolate/Core/src/Types/Types/Pagination/PagingHelper.cs:49]: This is the issue

new TypeDependency(
                             TypeReference.Create(schemaType, TypeContext.Output),
                                                     TypeDependencyKind.Named));

File: src/HotChocolate/Core/src/Types/Types/Pagination/PagingHelper.cs [hunk 4]
```diff
@@ -33,30 +33,24 @@ public static class PagingHelper
...
+                                c, d, entityType, resolvePagingProvider, options, placeholder)
+                        });
                 });
 
             return descriptor;
         }
 
+        // User => Group
+        // User => Collection => Group
+
```
Comment (PascalSenn) [inline src/HotChocolate/Core/src/Types/Types/Pagination/PagingHelper.cs:53]: Remove

**Review by michaelstaib — APPROVED** [review]

**Review by michaelstaib — APPROVED** [review]
