### PR TITLE
Fixed mutation convention context data

### LINKED ISSUE #4576: Incorrect Schema When Using Mutation Conventions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using [mutation conventions](https://chillicream.com/docs/hotchocolate/defining-a-schema/mutations/#conventions) and explicitly defining the type and field name for payload, it produces the incorrect schema. 

According to the documentation, the **PayloadFieldName** is the name of the field in the payload that represents the data....

```graphql
type Mutation {
  createUser(input: CreateUserCustomInput): CreateUserPayload
}

type CreateUserPayload {
   thisIsTheFieldName: User
   errors: [CreateUserError!]
}
```

... and **PayloadTypeName** is the type name of the payload.

```graphql
type Mutation {
  createUser(input: CreateUserCustomInput): ThisIsTheTypeName
}
```

Here is the C# code.

```csharp
[UseMutationConvention(
        InputArgumentName = "input", 
        InputTypeName = "HelloWorldInput", 
        PayloadFieldName = "message", 
        PayloadTypeName = "HelloWorldPayload"
)]
public string HelloWorldAsync(string name)
{
    return $"Hello, {name}!";
}
```

Expected schema:

```graphql
type Mutation {
  helloWorldAsync(input: HelloWorldInput!): HelloWorldPayload!
}

input HelloWorldInput {
  name: String!
}

type HelloWorldPayload {
  message: String
}
```

Actual schema:

```graphql
type Mutation {
  helloWorldAsync(input: HelloWorldInput!): message!
}

input HelloWorldInput {
  name: String!
}

type message {
  HelloWorldPayload: String
}
```

In the actual schema, the field and type name are switched.

One thing to note, I've tried this without explicitly defining type and field names (no arguments in mutation convention attribute), and the schema got the payload type correct (based on convention), but the payload field name is string, (which I assume is working as intended since I am only returning a string, not an object.)

Please let me know if I need more information. I am happy to provide more! And lastly, I am new to GraphQL so I may be getting things wrong. If so, let me know! 

Thanks!

### Steps to reproduce

1. Create a mutation that uses the mutation convention. 
2. Ensure that the mutation method returns a string, or any type that isn't an object.
3. In the convention, explicitly define the Payload field and type name.

### Relevant log output

_No response_

### Additional Context?

_No response_

### Product

Hot Chocolate

### Version

12.4.0

### PR DESCRIPTION
**Pull request by PascalSenn**
Closes #4576

### CODE REVIEW

File: src/HotChocolate/Core/src/Types.Mutations/MutationContextData.cs [hunk 1]
```diff
@@ -10,8 +10,8 @@ internal class MutationContextData
         ObjectFieldDefinition definition,
         string? inputTypeName,
         string? inputArgumentName,
-        string? payloadFieldName,
         string? payloadTypeName,
+        string? payloadFieldName,
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Types.Mutations/MutationContextData.cs:14]: can you also swap the initialization?

 PayloadFieldName = payloadFieldName;
        PayloadTypeName = payloadTypeName;

**Review by michaelstaib — APPROVED** [review]
