### PR TITLE
Fixed nullable matrix types in schema first.

### LINKED ISSUE #2966: Problem on stitching with a field of type `[[Int!]!]!`
One of our GraphQL .NET classes has the property of type `List<List<int>>`
which results in `[[Int!]!]!` in the schema. This does not seem to be a problem
as such until we try to stitch such a schema. Both `AddRemoteSchemaFromFile`
and `AddRemoteSchema` fail with some vague `SchemaException` "Specified method
is not supported." error.

[Slack]: https://hotchocolategraphql.slack.com/archives/CN3EZ03U1/p1612011860021100
As discussed on [Slack], this looks like a bug.

**Reproduction steps**

Please use the attached `StitchingIssue`. It is the simplified `ChilliCream\hotchocolate-examples\misc\Stitching\centralized`.
It only has `accounts` and `gateway` services.

`accounts` is changed so that its class `User` has this property (problematic on stitching):

    public List<List<int>> ProblemList { get; set; }

`gateway` is changed to connect just `accounts` and add its schema by `AddRemoteSchema`.

Build the solution.

Start `accounts` with port 5051 (already configured in `appsettings.json`).

Start `gateway`, open Banana Cake Pop, see errors in the console.
If BCP was already opened, try to reload the schema for the same effect.

**Error message and stack trace**

```
  Connection id "0HM654JDOA96O", Request id "0HM654JDOA96O:00000003": An unhandled exception was thrown by the application.
  HotChocolate.SchemaException: For more details look at the `Errors` property.

  1. Specified method is not supported.

     at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
     at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
     at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)
     at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
     at HotChocolate.SchemaBuilder.Create()
     at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
     at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
     at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass5_0.<<AddRemoteSchema>b__2>d.MoveNext()
  --- End of stack trace from previous location ---
     at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
     at HotChocolate.Execution.RequestExecutorProxy.GetSchemaAsync(CancellationToken cancellationToken)
     at HotChocolate.AspNetCore.ToolOptionsFileMiddleware.Invoke(HttpContext context)
     at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
     at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
     at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
     at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
     at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

---

[StitchingIssue.zip](https://github.com/ChilliCream/hotchocolate/files/5898089/StitchingIssue.zip)

### PR DESCRIPTION
**Pull request by PascalSenn**
We had a bug in unwrapping `ITypeNode`. We just did not unwrap enough

Closes #2966

### CODE REVIEW

File: src/HotChocolate/Language/src/Language.SyntaxTree/Extensions/TypeNodeExtensions.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ public static ITypeNode NullableType(this ITypeNode type)
 
         public static NamedTypeNode NamedType(this ITypeNode type)
         {
-            if (type.InnerType().InnerType().InnerType() is NamedTypeNode n)
+            if (type.InnerType().InnerType().InnerType().InnerType().InnerType() is NamedTypeNode n)
```
Comment (PascalSenn) [inline src/HotChocolate/Language/src/Language.SyntaxTree/Extensions/TypeNodeExtensions.cs:44]: @michaelstaib  Another argument against `[[[Int]]]`. 
It would not fit on a single line

**Review by michaelstaib — APPROVED** [review]
