### PR TITLE
Issue 4957 Correct problem with  Apollo Federation entity resolver bypassing dataloader

### LINKED ISSUE #4957: Dataloader does not behave correctly with Apollo Federation Resolvers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using a dataloader for the apollo federation resolver does not batch up the keys and send to dataloader in one shot.  

This was discussed on the slack channel under apollo-federation and @michaelstaib was kind enough to provide me direction on how to correct it.  

(I will have a draft PR up soon for review)

### Steps to reproduce

1.  Create a type that uses a data loader as follows:

```
My ObjectType....
.....
        protected override void Configure(IObjectTypeDescriptor<MyExposedObj> descriptor)
        {
            base.Configure(descriptor);
            descriptor.Name("MyExposedObj");
            descriptor.Key("id")
                .ResolveReferenceWith(om => ResolveMyExposedObj(default!, default!));
            descriptor.Field(_ => _.Id).Type<IdType>();
        }

        private static async Task<MyExposedObj> ResolveMyExposedObj(string id, MyDataLoader loader)
        {
            var l = Guid.Parse(id);
            return await loader.LoadAsync(l);
        }
....
```

2.  Execute a query that would be used by AF to resolve the type:
```
query {
  _entities(
    representations: [
      {
        __typename: "ObjectType"
        id: "3d178bb7-807b-42c0-ad64-911da6b00b10"
      }
      {
        __typename: "ObjectType"
        id: "cd904259-5522-44b7-8a6b-e10c070fea0c"
      }
            {
        __typename: "ObjectType"
        id: "dd90eb30-8928-47b5-978c-3294d8bc4246"
      }
    ]
  ) {
    ... on ObjectType {
      Id
      OtherField
      }
    }
  }
}

```

3.  The dataloader will be executed 3 times instead of once with a batch of ids (caching will work though)

### Relevant log output

_No response_

### Additional Context?

_No response_

### Product

Hot Chocolate

### Version

12.6.0

### PR DESCRIPTION
**Pull request by mightymiracleman**
Correct problem with Apollo Federation resolver not using data loader

Summary of the changes (Less than 80 chars)

- Alter EntityResolver to create array of tasks then iterate over them / add test

 I had to reference the GreenDonut.Tests project to use the ManualBatchScheduler class; if this isn't ok let me know and I'll rework.  Also; if you feel I need to add more tests around this please let me know and I will.  I had thought it was ok; but I can certainly add more.

Closes #4957

### CODE REVIEW

**Comment by mightymiracleman** [comment]
made mis

**Comment by mightymiracleman** [comment]
Hello, still hoping to get this reviewed and merged in.

File: src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs [hunk 1]
```diff
@@ -16,34 +16,75 @@ internal static class EntitiesResolver
         IReadOnlyList<Representation> representations,
         IResolverContext context)
     {
-        var entities = new List<object?>();
+        Task<object?>[] tasks = ArrayPool<Task<object?>>.Shared.Rent(representations.Count);
+        tasks.AsSpan().Slice(0, representations.Count).Clear();
```
Comment (PascalSenn) [inline src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs:20]: @michaelstaib  i dont think this clearing is necessary as we anyway re-assign each index of `repesentations.Count` and only iterate until `representations.Count`

**Review by PascalSenn — APPROVED** [review]

**Comment by PascalSenn** [comment]
@mightymiracleman  Thanks for the PR! 

Sorry that it took so long, we are quite busy with a lot of things ;)

I pushed a few commits, mainly formatting. 
I also replaced the Linq foreach with a for loop to reduce allocation and readability

File: src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs (hunk 1 above)
Comment (mightymiracleman) [reply src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs:20]: Got it makes sense.

**Comment by mightymiracleman** [comment]
> @mightymiracleman Thanks for the PR!
> 
> Sorry that it took so long, we are quite busy with a lot of things ;)
> 
> I pushed a few commits, mainly formatting. I also replaced the Linq foreach with a for loop to reduce allocation and readability

Sounds great!  When do you think this will merge?  Thanks for reviewing it and the feedback.  Hope I can give back more in the future.

File: src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs (hunk 1 above)
Comment (michaelstaib) [reply src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs:20]: We should clear at the end so that the GC can collect the tasks. We often also clear at the beginning if there is a possibility that we could access something old :)

If that is guaranteed to not happen because we are setting everything then fine...

Comment (michaelstaib) [reply src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs:20]: Also make sure to use the indexer only once per iteration.

Comment (PascalSenn) [reply src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs]: @michaelstaib  accessing the indexer once per iteration is not really possible. Coudl only reduce it by one access for the first loop.
Array is now cleared by. calling .Return(tasks, true) and not cleared in the beginning.

File: src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs [hunk 2]
```diff
@@ -11,39 +11,79 @@ namespace HotChocolate.ApolloFederation.Helpers;
 /// </summary>
 internal static class EntitiesResolver
 {
-    public static async Task<List<object?>> ResolveAsync(
+    public static async Task<IReadOnlyList<object?>> ResolveAsync(
```
Comment (PascalSenn) [inline src/HotChocolate/ApolloFederation/src/ApolloFederation/Helpers/EntitiesResolver.cs:14]: @michaelstaib  as this a internal resolver i changed it to List. we save a list allocation by doing this.

**Comment by willwolfram18** [comment]
@michaelstaib @PascalSenn Is there an ETA on when this can be merged and released? This would be an invaluable addition to the Apollo Federation implementation in HC! My team is evaluating using HC for a federated API right now and would love to have the performance benefit of a data loader to retrieve that data 👍

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
@willwolfram18 It's done ... just waited for my sign of.

**Comment by michaelstaib** [comment]
I will cherry pick it on 12.10
