### PR TITLE
Fixed memory leaks in subscriptions

### LINKED ISSUE #2740: Subscription resolvers aren't disposed immediately when unsubscribing
I’ve noticed that when unsubscribing to a subscription client-side, the subscription resolver will still keep running, as long as the WS connection remains active. Only when disconnecting the WS (e.g. refreshing the page, or closing the tab), the server-side event receiver stops for the subscriptions of this client.

```
[SubscribeAndResolve]
public async IAsyncEnumerable<Foo> OnFooAsync(
    Guid someId,
    [Service] ITopicEventReceiver eventReceiver,
    [Service] ILogger<MessageSubscriptions> logger,
    [EnumeratorCancellation] CancellationToken cancellationToken)
{ 
    logger.LogInformation($"Started subscription for {someId}");

    var stream = await eventReceiver.SubscribeAsync<string, Foo>(
        $”foo-{someId}”, cancellationToken);

    var enumerator = stream.ReadEventsAsync().GetAsyncEnumerator(cancellationToken);
    var hasResult = true;
            
    while (hasResult)
    {
        Foo? result;
        try
        {
                     hasResult = await enumerator.MoveNextAsync().ConfigureAwait(false);
            
                     result = hasResult 
                         ? enumerator.Current 
                         : null;
                 }
                 catch (Exception ex)
                 {
                     if (ex is not OperationCanceledException)
                     {
                         logger.LogError(ex, $"Error in subscription for {someId}");
                     }
                     
                     result = null;
                 }
                 if (result != null)
                 {
                     yield return result;
                 }
     }

    logger.LogInformation($"Terminated subscription for {someId}”);
}
```

I’d expect the “Terminated subscription …” to be logged as soon as the subscription is stopped, but that’s not happening. Instead I’m seeing is that the “await foreach” keeps running until the WS eventually is disconnected, even if the subscription was stopped on the client-side. For long-lived client sessions I imagine this could potentially turn into an memory leak issue down the road.

### LINKED ISSUE #3595: OperationContext is not disposed in subsriptions (memory leak)
Looks like HotChocolate has serious memory leaks in subscriptions when InMemoryPubSub is used (and probably with other PubSub too). Subscription and all related stuffs like operation context, execution context, etc are leaked because of ExecutionContext subscribes to event TaskEnqueued in batch dispatcher, but never unsubscribes from it. Taking into account that static batch dispatcher NoopBatchDispatcher is used for subscriptions it causes leak. Look at the code below

```
            // subscribe will use the subscribe resolver to create a source stream that yields
            // the event messages from the underlying pub/sub-system.
            private async ValueTask<ISourceStream> SubscribeAsync()
            {
                OperationContext operationContext = _operationContextPool.Get();
                try
                {
                    // first we will create the root value which essentially
                    // is the subscription object. In some cases this object is null.
                    object? rootValue = RootValueResolver.Resolve(
                        _requestContext,
                        _requestContext.Services,
                        _subscriptionType,
                        ref _cachedRootValue);
                    // next we need to initialize our operation context so that we have access to
                    // variables services and other things.
                    // The subscribe resolver will use a noop dispatcher and all DataLoader are
                    // dispatched immediately.
                    operationContext.Initialize(
                        _requestContext,
                        _requestContext.Services,
                        NoopBatchDispatcher.Default,
                        _requestContext.Operation!,
                        _requestContext.Variables!,
                        rootValue,
                        _resolveQueryRootValue);
                    // next we need a result map so that we can store the subscribe temporarily
                    // while executing the subscribe pipeline.
                    ResultMap resultMap = operationContext.Result.RentResultMap(1);
                    ISelection rootSelection = _rootSelections.Selections[0];
                    // we create a temporary middleware context so that we can use the standard
                    // resolver pipeline.
                    var middlewareContext = new MiddlewareContext();
                    middlewareContext.Initialize(
                        operationContext,
                        rootSelection,
                        resultMap,
                        1,
                        rootValue,
                        Path.New(rootSelection.ResponseName),
                        ImmutableDictionary<string, object?>.Empty);
                    // it is important that we correctly coerce the arguments before
                    // invoking subscribe.
                    if (!rootSelection.Arguments.TryCoerceArguments(
                        middlewareContext.Variables,
                        middlewareContext.ReportError,
                        out IReadOnlyDictionary<NameString, ArgumentValue>? coercedArgs))
                    {
                        // the middleware context reports errors to the operation context,
                        // this means if we failed, we need to grab the coercion errors from there
                        // and just throw a GraphQLException.
                        throw new GraphQLException(operationContext.Result.Errors);
                    }
                    // if everything is fine with the arguments we still need to assign them.
                    middlewareContext.Arguments = coercedArgs;
                    // last but not least we can invoke the subscribe resolver which will subscribe
                    // to the underlying pub/sub-system yielding the source stream.
                    ISourceStream sourceStream =
                        await rootSelection.Field.SubscribeResolver!.Invoke(middlewareContext)
                            .ConfigureAwait(false);
                    if (operationContext.Result.Errors.Count > 0)
                    {
                        // again if we have any errors we will just throw them and not opening
                        // any subscription context.
                        throw new GraphQLException(operationContext.Result.Errors);
                    }
                    return sourceStream;
                }
                finally
                {
                    operationContext.Result.DropResult();
                    _operationContextPool.Return(operationContext);
                }
            }

```
Unsubscribe from event is happened only if operation context is returned to the pool, but it doesn't happen because of object doesnt meet pool return policy OperationContextPoolPolicy requirements  (condition obj.Execution.TaskStats.IsCompleted is not true).

### PR DESCRIPTION
**Pull request by akolpachev**
Outgoing channel is closed now if related subscription or websocket is closed. MessageReceiver is stopped if error happens in linked message processor. OperationContext is marked as completed in subscribe operation. 

Closes #2740
Closes #3595

### CODE REVIEW

**Comment by michaelstaib** [comment]
Great .... thanks for putting this together ... we will do a review tonight.

**Comment by akolpachev** [comment]
Fixed tests

File: src/HotChocolate/AspNetCore/src/AspNetCore/Subscriptions/Subscription.cs [hunk 1]
```diff
@@ -39,51 +41,64 @@ internal sealed class Subscription : ISubscription
...
+                        finally
+                        {
+                            await _connection.SendAsync(new DataCompleteMessage(Id), cancellationToken);
+                        }
+
                     }
+                    catch { } // suppress all errors, so original exception can be rethrown
                 }
+
+                // original exception should be propagated to upper level in order to be logged correctly at least
```
Comment (michaelstaib) [inline src/HotChocolate/AspNetCore/src/AspNetCore/Subscriptions/Subscription.cs:95]: Throwing the exception here will not really help logging. I think we should inject the IDiagnostEvenets and log the error.

File: src/HotChocolate/AspNetCore/src/AspNetCore/Subscriptions/Subscription.cs [hunk 2]
```diff
@@ -39,51 +42,65 @@ internal sealed class Subscription : ISubscription
...
-                    finally
+                    catch
                     {
-                        await _connection.SendAsync(new DataCompleteMessage(Id), _cts.Token);
-                        Completed?.Invoke(this, EventArgs.Empty);
+                        // suppress all errors, so original exception can be rethrown
                     }
                 }
+
+                // original exception should be propagated to upper level in order to be logged
```
Comment (michaelstaib) [inline src/HotChocolate/AspNetCore/src/AspNetCore/Subscriptions/Subscription.cs:95]: We will remove this in favor of proper diagnostic events. I will add a new diagnostic event tomorrow and we will pass the through the the diagnostic events.

File: src/HotChocolate/Core/src/Execution/Processing/SubscriptionExecutor.Subscription.cs [hunk 3]
```diff
@@ -202,6 +205,9 @@ private async ValueTask<ISourceStream> SubscribeAsync()
                         await rootSelection.Field.SubscribeResolver!.Invoke(middlewareContext)
                             .ConfigureAwait(false);
 
+                    // mark operation context as Completed in order to free all associated resources and allow to return it to pool
+                    ((IExecutionTaskContext)operationContext).Completed();
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Execution/Processing/SubscriptionExecutor.Subscription.cs:209]: Does it really complete?

The task context is for internal execution tasks to mark their work as completed. The issue here is that it will rain the completed count by one and the compare completed to enqueued tasks which would fail and block completion. The context would then be abandoned.

There is one more use case in this scenario I worry about. I will have a look at this particular piece. In the our issue case here we want to mark this operation as completed since we no it actually has not pending work.

I will have a look at this in the morning.

side-note for myself :)

In the case we have pending work and we need to abandon the context to to errors we need to ensure that we still clean and unsubscribe.

**Comment by michaelstaib** [comment]
TODO @michaelstaib 

- [ ] Subscription Diagnostics
- [ ] Error Cases (safely abandon contexts)
- [ ] Completion Handling
- [ ] Formatting

**Comment by michaelstaib** [comment]
@akolpachev I have a small todo list for this which I will work through tomorrow. This I great work. We will merge it once I have ticked of my items on this probably tomorrow afternoon. It will be included into the next preview.

File: src/HotChocolate/AspNetCore/src/AspNetCore/Subscriptions/Subscription.cs (hunk 1 above)
Comment (akolpachev) [reply src/HotChocolate/AspNetCore/src/AspNetCore/Subscriptions/Subscription.cs]: Well, app developer can always log exception from not-awaited task if add handler to TaskScheduler.UnobservedTaskException, so such exceptions can be logged if desired. In any case I will add IDiagnosticEvents.

**Comment by akolpachev** [comment]
Nice. Thank you.

File: src/HotChocolate/Core/src/Execution/Processing/SubscriptionExecutor.Subscription.cs [hunk 4]
```diff
@@ -127,6 +127,9 @@ private async Task<IQueryResult> OnEvent(object payload)
                     return await _queryExecutor
                         .ExecuteAsync(operationContext, scopedContext)
                         .ConfigureAwait(false);
+
+                    // I believe operation context should be marked as completed here?
```
Comment (akolpachev) [inline src/HotChocolate/Core/src/Execution/Processing/SubscriptionExecutor.Subscription.cs:131]: @michaelstaib  Could you please look at this comment? I left it, because I believe that operation context should be completed here, but of course I dont understand all code mechanics. Please remove it if it is wrong.

File: src/HotChocolate/AspNetCore/src/AspNetCore/Subscriptions/Subscription.cs (hunk 1 above)
Comment (michaelstaib) [reply src/HotChocolate/AspNetCore/src/AspNetCore/Subscriptions/Subscription.cs]: I have done the events now.

Comment (michaelstaib) [reply src/HotChocolate/AspNetCore/src/AspNetCore/Subscriptions/Subscription.cs]: The reason for not to rely on `TaskScheduler.UnobservedTaskException` is that. the telemetry api should be the go to to get such insights.

File: src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs [hunk 5]
```diff
@@ -22,12 +21,20 @@ public bool Return(OperationContext obj)
...
+                    obj.Execution.TaskStats.NewTasks == 0 &&
+                    obj.Execution.TaskStats.CompletedTasks == 0))
             {
                 obj.Clean();
                 return true;
             }
 
+            // we also clean if we cannot reuse the context so that the context is
+            // gracefully discarded and can be garbage collected.
+            obj.Clean();
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs:37]: we now in any case call clean here.

File: src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs [hunk 6]
```diff
@@ -22,12 +21,20 @@ public bool Return(OperationContext obj)
                 return true;
             }
 
-            if (obj.Execution.TaskStats.IsCompleted)
+            // if work related to the operation context has completed or if it never started
+            // we can reuse the operation context.
+            if (obj.Execution.TaskStats.IsCompleted ||
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs:26]: The case for reusing a context is now broader. Meaning if we have an early abort by a query, mutation or subscription we also will reuse the context.

File: src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs (hunk 5 above)
Comment (akolpachev) [reply src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs:37]: I doubt. Does it safe to clean context if tasks have not completed yet (obj.Execution.TaskStats.IsCompleted = false and NewTasks != 0 in condition above)?

File: src/HotChocolate/Core/src/Execution/Processing/SubscriptionExecutor.Subscription.cs (hunk 4 above)
Comment (michaelstaib) [reply src/HotChocolate/Core/src/Execution/Processing/SubscriptionExecutor.Subscription.cs]: This is now solved. I reworked the policy to better reuse contexts and always clean them.

File: src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs (hunk 5 above)
Comment (michaelstaib) [reply src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs:37]: In this case we are in an error case where the execution was aborted but there are still some tasks running that are waiting to be aborted. This happens in cases where users forget to honor the cancellation token. We do not want to reuse the context in this case since tasks could still be mutation the context. But, we need to actually clean it so that this can be garbage collected. In this case we are already in an error state and the tasks still running are running in error meaning if they fail because we clear the context should not really matter.

Comment (michaelstaib) [reply src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs:37]: Or is your concern that the clean could have an exception?

Comment (akolpachev) [reply src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs:37]: I understand now. All is good. One note that Clean method set _isPooled = true, but it is not actually truth in that case (context will be garbaged at the end). However I believe it doesn't matter.

**Comment by michaelstaib** [comment]
I am done with the PR. If you two (@akolpachev, @PascalSenn) would have another look through it I would be thankful.

**Review by michaelstaib — APPROVED** [review]

File: src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs (hunk 5 above)
Comment (michaelstaib) [reply src/HotChocolate/Core/src/Execution/Processing/OperationContextPoolPolicy.cs:37]: I have renamed that to IsInitialized.

**Review by michaelstaib — APPROVED** [review]

**Comment by michaelstaib** [comment]
Tests look good ... The sonar build error is due to a flaky test. So no worries there.

**Comment by michaelstaib** [comment]
@PascalSenn I would be read to merge if you give me thumbs up.

File: src/HotChocolate/Core/src/Execution/Instrumentation/NoOpDiagnosticEvents.cs [hunk 7]
```diff
@@ -44,13 +45,24 @@ internal sealed class NoopDiagnosticEvents
...
-        
-        public void AddedDocumentToCache(
-            IRequestContext context)
+
+        public IActivityScope ExecuteSubscription(ISubscription subscription) => this;
+
+        public IActivityScope OnSubscriptionEvent(SubscriptionEventContext context) => this;
+
+        public void SubscriptionEventResult(SubscriptionEventContext context, IQueryResult result)
+        {  }
```
Comment (PascalSenn) [inline src/HotChocolate/Core/src/Execution/Instrumentation/NoOpDiagnosticEvents.cs:54]:
```suggestion
        { }
```
