### PR TITLE
Don't assume default value for optional value type argument without default value

### LINKED ISSUE #6347: Inconsistent behavior within InputParser, when parse nullable scalar value in HC 13 in compare with 12
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

If there is a input type which has 2 fields like
```
{
documentId: String
revision: Int
}
```
If the query with this input type argument run like:
```
query myquery {
                       tests{
                         test(documentVersion: {documentId: "myid", revision: null}) {
                           revision
                         }
                       }
                     }
```
InputParser parse "revision" as null - which is expected, but in case the query run without "revision" parameter InputParser parse it as default Int32 value - 0.

HC 12 code retuned null in both cases.

It happens here, which I think is incorrect behavior:
https://github.com/ChilliCream/graphql-platform/blob/96b9a9c4198d7f13a15b10f617f536c1ca15d3c6/src/HotChocolate/Core/src/Types/Types/InputParser.cs#L662

the code comment says:
            // if the type is nullable but the runtime type is a non-nullable value
            // we will create a default instance and assign that instead.
which makes no sense to me, if the field nullable why it's need to forcedly set to default not nullable value?

### Steps to reproduce

1. Build/Run attached [repro.zip](https://github.com/ChilliCream/graphql-platform/files/12078361/repro.zip) project
2. Open "serverPath/graphql/ui" Banana Cake url
3. Run query:
```
query  myquery{
    testData (documentVersion: {documentId: "mydocId", revision: null}){
      id
    }
}
```
4. Note that revision field is null within resolver method, which is expected.
2023-07-18 10_40_56-WebApplication1 – TestDataResolver cs  Debugger
5. Run another query, without revision parameter specifying:
```
query  myquery{
    testData (documentVersion: {documentId: "mydocId"}){
      id
    }
} 
```
6. Note that this time revision fields is equals 0, which is not expected for nullable field.
2023-07-18 10_40_34-WebApplication1 – TestDataResolver cs  Debugger

### Relevant log output

_No response_

### Additional Context?

_No response_

### Version

13.3.3

### PR DESCRIPTION
**Pull request by N-Olbert**
- Don't assume default value for optional value type argument without default value

Closes #6347 (in this specific format)

Background:

This issue appears to be a side effect of #5317 and/or #4354.
If an optional value type argument was not present in the input arguments, the InputParser was changed in 5317 to emit the default value for that type.
This was necessary to avoid compilation failures as `null` can not be converted to the value type.

This PR removes this special handling from the InputParser and instead coalesces null arguments into the default value within the compiler itself.
This approach is very similar to how optional values are handled and allows the InputParser to correctly preserve an explicit null argument.

General note: This seems to only affects code-first types. For annotation-based types, we already have the correct nullability information, as an argument of type int? is in fact a Nullable<int> whose default value is null. 
Anyhow, for code-first types, this is not the case as f. e. `BooleanType` maps to the runtime-type `bool` instead of `Nullable<bool>`.

### CODE REVIEW

**Comment by glen-84** [comment]
Can you please revert the formatting changes? 🙂

**Comment by N-Olbert** [comment]
Whoops... done

File: src/HotChocolate/Core/src/Types/Utilities/Serialization/InputObjectCompiler.cs [hunk 1]
```diff
@@ -243,6 +243,11 @@ private static void CompileSetProperties<T>(
             {
                 value = CreateOptional(value, field.RuntimeType);
             }
+            else if (field.Property.PropertyType.IsValueType
+                     && System.Nullable.GetUnderlyingType(field.Property.PropertyType) == null)
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Types/Utilities/Serialization/InputObjectCompiler.cs]:
```suggestion
            else if (field.Property.PropertyType.IsValueType
                && System.Nullable.GetUnderlyingType(field.Property.PropertyType) == null)
```

File: src/HotChocolate/Core/test/Types.Tests/Types/InputParserTests.cs [hunk 2]
```diff
@@ -493,6 +493,55 @@ public void Force_NonNull_Struct_To_Be_Optional()
...
+    {
+        // arrange
+        var resolverArgumentsAccessor = new ResolverArgumentsAccessor();
+        var executor = await new ServiceCollection()
+            .AddSingleton(resolverArgumentsAccessor)
+            .AddGraphQL()
+            .AddQueryType(x => x.Field("foo")
+                                .Argument("args", a => a.Type<NonNullType<MyInputType>>())
+                                .Type<StringType>()
+                                .ResolveWith<ResolverArgumentsAccessor>(r => r.ResolveWith(default!)))
```
Comment (michaelstaib) [inline src/HotChocolate/Core/test/Types.Tests/Types/InputParserTests.cs]:
```suggestion
            .AddQueryType(x => x.Field("foo")
                .Argument("args", a => a.Type<NonNullType<MyInputType>>())
                .Type<StringType>()
                .ResolveWith<ResolverArgumentsAccessor>(r => r.ResolveWith(default!)))
```
