### PR TITLE
Fixed Variable Coercion of Nullable Enum Values

### LINKED ISSUE #4263: Order does not work when used in query variable
### Describe the bug

If you hardcode order like `order: DESC` query works but if you use variable `order: $order` then it does not.

Might be related to https://github.com/ChilliCream/hotchocolate/issues/2475

### Steps to reproduce

https://github.com/kolpav/HotChoco/tree/order-bug

OK

https://user-images.githubusercontent.com/19467143/134618817-e269145c-ce70-4a8a-a883-32d43d6a46c8.mp4

NOK

https://user-images.githubusercontent.com/19467143/134618811-fb6ff4fb-31d1-4b48-8a30-fe976027706e.mp4

### Product

Hot Chocolate

### Version

12.0.0-rc.11

### PR DESCRIPTION
**Pull request by PascalSenn**
Closes #4263

### CODE REVIEW

File: src/HotChocolate/Core/src/Execution/Processing/VariableCoercionHelper.cs [hunk 1]
```diff
@@ -142,10 +142,11 @@ public VariableCoercionHelper(InputFormatter inputFormatter, InputParser inputPa
                 case ListValueNode lv:
                     return Rewrite(inputType, lv);
 
-                case StringValueNode sv:
-                    return inputType.Kind is TypeKind.Enum
-                        ? new EnumValueNode(sv.Location, sv.Value)
-                        : node;
+                case StringValueNode sv when inputType.IsEnumType():
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Execution/Processing/VariableCoercionHelper.cs:145]: I have simplified this to the IsEnumType since I have optimized the implementation of IsEnumType to check the kind instead of the type.

File: src/HotChocolate/Core/src/Execution/Processing/VariableCoercionHelper.cs [hunk 2]
```diff
@@ -209,12 +225,23 @@ private static ListValueNode Rewrite(IType inputType, ListValueNode node)
...
+                // we try initially just to traverse the list graph, only if we detect a change
+                // will we create a new list object. In this case if values list is initialized
+                // we know that we have already collected at least one change. In this case
+                // all further value nodes have to be added as well even if they do not have
+                // a changed value since we need to produce a complete new list value node.
                 if (values is not null)
                 {
                     values.Add(value);
                 }
-                else if (!ReferenceEquals(current.Value, value))
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Execution/Processing/VariableCoercionHelper.cs:216]: This is why integration tests are never enough.

**Review by michaelstaib — APPROVED** [review]
