### PR TITLE
Fixed Issue #629

### LINKED ISSUE #629: Custom diagnostic sources only work when Apollo Tracing is enabled.

### PR DESCRIPTION
**Pull request by rstaib**
Fixes #629

### CODE REVIEW

File: src/Core/Core/Execution/Instrumentation/ApolloTracingDiagnosticObserver.cs [hunk 1]
```diff
@@ -115,5 +150,14 @@ private static long GetStartTimestamp()
             return Convert.ToInt64(Activity.Current.Tags
                 .First(t => t.Key == _startTimestampKey).Value);
         }
+
+        private bool IsEnabled(object context)
```
Comment (michaelstaib) [inline src/Core/Core/Execution/Instrumentation/ApolloTracingDiagnosticObserver.cs]: So, the outer IsEnabled is now completely obsolete?
To have it here in the Apollo Tracing Observer seems even to make more sense, since this is only related to this specific observer.

**Comment by michaelstaib** [comment]
do not forget to update the build solutions in the tools folder, I think this is why it does not build.


tools/Build.sln and tools/Build.Core.sln

**Comment by michaelstaib** [comment]
I will start updating the documentation for this one...

**Comment by michaelstaib** [comment]
The build is now fixed.
