### PR TITLE
Fixed Issue with sorting and GraphQLType

### LINKED ISSUE #4415: Issue with in-memory sorting of Date fields
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running into an issue with HotChocolate.Data.UseSorting on a C# DateTime field that's exposed as a [GraphQLType(typeof(NonNullType<DateType>))] field on 11.3.8.

### Steps to reproduce

Create a type like:

```csharp
public class MyClass
{
    [GraphQLType(typeof(NonNullType<DateType>))]
    public DateTime CreatedUtc { get; set; }
}
```

Expose it on a field like this:

```csharp
public class Query
{
    [UseSorting] public IEnumerable<MyClass> MyClasses() => ...
}
```

Then try to query it. _edit: make sure to sort by the date field during the query_

Note the stack trace below

### Relevant log output

```shell
Stack trace:
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)\r\n   at HotChocolate.Data.Sorting.Expressions.SortExpressionBuilder.IfNullThenDefault(Expression left, Expression right, DefaultExpression defaultExpression)\r\n   at HotChocolate.Data.Sorting.Expressions.QueryableDefaultSortFieldHandler.TryHandleEnter(QueryableSortContext context, ISortField field, ObjectFieldNode node, ISyntaxVisitorAction& action)\r\n   at HotChocolate.Data.Sorting.SortVisitor`2.OnFieldEnter(TContext context, ISortField field, ObjectFieldNode node)\r\n   at HotChocolate.Data.Sorting.SortVisitorBase`2.Enter(ObjectFieldNode node, TContext context)\r\n   at HotChocolate.Language.Visitors.SyntaxWalker`1.Enter(ISyntaxNode node, TContext context)\r\n   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)\r\n   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ObjectValueNode node, TContext context)\r\n   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)\r\n   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)\r\n   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit(ISyntaxNode node, TContext context)\r\n   at HotChocolate.Data.Sorting.Expressions.QueryableSortProvider.<>c__DisplayClass9_0.<ConfigureField>g__VisitSortArgumentExecutor|0(IValueNode valueNode, ISortInputType filterInput, Boolean inMemory)\r\n   at HotChocolate.Data.Sorting.Expressions.QueryableSortProvider.<>c__DisplayClass8_0`1.<<CreateExecutor>g__ExecuteAsync|1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Types.Pagination.PagingMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### Additional Context?

_No response_

### Product

Hot Chocolate

### Version

11.3.5-11.3.8

### PR DESCRIPTION
**Pull request by PascalSenn**
Closes #4415

### CODE REVIEW

File: src/HotChocolate/Data/src/Data/Sorting/Fields/SortField.cs [hunk 1]
```diff
@@ -38,7 +38,7 @@ internal SortField(SortFieldDefinition definition, int index)
 
             if (Member?.DeclaringType is not null)
             {
-                RuntimeType = context.TypeInspector.GetReturnType(Member);
+                RuntimeType = context.TypeInspector.GetReturnType(Member, ignoreAttributes: true);
```
Comment (michaelstaib) [inline src/HotChocolate/Data/src/Data/Sorting/Fields/SortField.cs:41]: line length?

Comment (PascalSenn) [reply src/HotChocolate/Data/src/Data/Sorting/Fields/SortField.cs:41]: image

**Review by michaelstaib — APPROVED** [review]
