### PR TITLE
Fixed type trimming. The trimmer no correctly visits directives.

### LINKED ISSUE #4712: Using 'RemoveUnreachableTypes' option in HC 12 breaks BCP (and other graphql IDEs)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using `.ModifyOptions(options => options.RemoveUnreachableTypes = true);` breaks Banana Pop Cake (and Insomnia).
I have been able to reproduce the issue using HC v.12.5 and v.12.6

### Steps to reproduce

1. Check out the Schema First demo example (from [here](https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/SchemaFirst))
2. Optionally remove the `[UsePaging]` attribute from the Query.GetPersons method.
This is to ensure that the generated schema does not include any auto-generated `Int` field
image
3. Add `.ModifyOptions(options => options.RemoveUnreachableTypes = true);` to Program.cs
image
4. Reproduce the problem by starting the demo application an hopping over to BCP. You should see a spinning doughnut as the fetched schema is not readable. Then open the [F12] Browser tools and see the following error message
image

### Relevant log output

_No response_

### Additional Context?

Digging a bit deeper to the root cause.

First look at the sdl and find that there is only one `Int` field (in the stream directive):
image

Second find the 'introspection_phase_2' query in the Network tab of the Browser tools:
image
Inspect the response in a tool like e.g. VS Code and you will see that effectively no `Int` SCALAR type has been defined. However, it's being used in the `scalar` directive...
image

Third repeat the same steps but this time without the `options.RemoveUnreachableTypes` option....
image

### Product

Hot Chocolate

### Version

12.6

### PR DESCRIPTION
**Pull request by vhatsura**
Summary of the changes

- Visit directive type during schema trim to add types from arguments into the final schema

Closes #4712

### CODE REVIEW

File: src/HotChocolate/Core/src/Types/Configuration/TypeTrimmer.cs [hunk 1]
```diff
@@ -39,6 +39,7 @@ public IReadOnlyCollection<TypeSystemObjectBase> Trim()
                 directiveType.Name.Equals(WellKnownDirectives.Deprecated))
             {
                 _touched.Add(directiveType);
+                VisitDirective(directiveType);
```
Comment (michaelstaib) [inline src/HotChocolate/Core/src/Types/Configuration/TypeTrimmer.cs:42]: can you add a test that shows the issue that this solves?

Comment (vhatsura) [reply src/HotChocolate/Core/src/Types/Configuration/TypeTrimmer.cs:42]: @michaelstaib, it was exactly my question how to write tests in a better way as a current approach for TypeTrimmer tests uses SchemaBuilder which doesn't print scalars, but I think I figured out how to deal with that

Comment (michaelstaib) [reply src/HotChocolate/Core/src/Types/Configuration/TypeTrimmer.cs:42]: In GraphQL built-in scalars are not printed. You can create a dummy scalar to test that.

Comment (michaelstaib) [reply src/HotChocolate/Core/src/Types/Configuration/TypeTrimmer.cs:42]: But what is the error that happens?

Comment (michaelstaib) [reply src/HotChocolate/Core/src/Types/Configuration/TypeTrimmer.cs:42]: Is the issue that we do not visit the query directives and thus remove a scalar that is important for the directive?

Comment (vhatsura) [reply src/HotChocolate/Core/src/Types/Configuration/TypeTrimmer.cs:42]: So, the trimmer has two inputs: discovered types and root types (tbh, I don't have any clue what discovered types mean here). When we iterate over root types we're using visitors which visit all directives and as a result visit all arguments. Iterating over directives from discovered types doesn't visit directives to analyze arguments and as a result, it can be the issue that one of the directives uses scalar or any other type which will not be in the final schema. In the original issue #4712 it was with `@stream` direcitive

Comment (vhatsura) [reply src/HotChocolate/Core/src/Types/Configuration/TypeTrimmer.cs:42]: @michaelstaib, I've added the test which validates my fix. W/o changes, the UUID scalar will not be a part of the final schema.

**Review by michaelstaib — APPROVED** [review]
