### PR TITLE
Fix Optional<IFile> in InputObject

### LINKED ISSUE #3621: Optional<IFile> not handled correctly in InputObjects
```csharp
public record UpdateUserInput(Optional<IFile> ProfilePicture);

public class Mutation
{
    public Payload UpdateUser(UpdateUserInput input)
    {
         // ...
    }
}
```

```graphql
mutation UpdateUser($file: Upload) {
  updateUser(input: { profilePicture: $file }) {
    result
  }
}
```

Executing a mutation against this defintion produces the following error:

```
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateUser"
      ],
      "extensions": {
        "message": "Unable to convert type from `UploadedFile` to `IFile`",
        "stackTrace": "   at HotChocolate.Utilities.DefaultTypeConverter.Convert(Type from, Type to, Object source)\r\n   at HotChocolate.Utilities.Serialization.InputObjectParserHelper.ConvertValue(InputField field, ITypeConverter converter, Object value)\r\n   at HotChocolate.Utilities.Serialization.InputObjectParserHelper.Parse(InputObjectType type, ObjectValueNode source, IDictionary`2 target, ITypeConverter converter)\r\n   at HotChocolate.Utilities.Serialization.InputObjectParserHelper.ParseLiteral(InputObjectType type, ObjectValueNode value, InputObjectFactory factory, ITypeConverter converter)\r\n   at HotChocolate.Types.InputObjectType.<>c__DisplayClass31_1.<OnCompleteType>b__4(ObjectValueNode ov)\r\n   at HotChocolate.Types.InputObjectType.ParseLiteral(IValueNode valueSyntax, Boolean withDefaults)\r\n   at HotChocolate.Execution.Processing.MiddlewareContext.CoerceArgumentValue[T](ArgumentValue argument)\r\n   at HotChocolate.Execution.Processing.MiddlewareContext.ArgumentValue[T](NameString name)\r\n   at HotChocolate.Execution.Processing.DirectiveContext.ArgumentValue[T](NameString name)\r\n   at lambda_method289(Closure , IResolverContext )\r\n   at HotChocolate.Types.FieldMiddlewareCompiler.<>c__DisplayClass3_0.<<CreateResolverMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Types.EntityFrameworkObjectFieldDescriptorExtensions.<>c__DisplayClass2_1`1.<<UseDbContext>b__4>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Types.EntityFrameworkObjectFieldDescriptorExtensions.<>c__DisplayClass2_1`1.<<UseDbContext>b__4>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.AspNetCore.Authorization.AuthorizeMiddleware.InvokeAsync(IDirectiveContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
      }
    }
  ],
  "data": {
    "updateUser": null
  }
}
```

### PR DESCRIPTION
**Pull request by tobias-tengler**
Closes #3621

### CODE REVIEW

**Comment by tobias-tengler** [comment]
@michaelstaib I'm too unfamiliar with the code to be able to solve this issue, but I think it should be something minor. Would be great if you could take a look! :)
I've already created the necessary tests that should pass, once `Optional<IFile>` works in InputObjects.

**Comment by michaelstaib** [comment]
I will check it out.

**Comment by LukasDJacobs** [comment]
Anything I could do to help this get into a release? Maybe have a look at the failing Sonar Tests?

**Comment by tobias-tengler** [comment]
> Anything I could do to help this get into a release? Maybe have a look at the failing Sonar Tests?

All I did in this PR thus far, was adding some failing tests to highlight the issue. I haven't yet looked at a fix, as I'm not that deep in the codebase yet and Michael said he wanted to take a look. Personally I also just forgot about it... sorry about that.
If you want to you can clone the repository, checkout this branch and try to diagnose the issue. Maybe you can find some useful pointers :) I'm currently at work so I can't do much, but if I get the time I'll try to look into it as well!

**Comment by LukasDJacobs** [comment]
No Problem, was just asking. Will probably try to take a look into this later on, think I might have the time for this in the afternoon.

**Comment by LukasDJacobs** [comment]
OK, so here's what I could find out being not too familiar with the internals of the project:
When trying to handle the request, HotChocolate tries to get or create a converter from `HotChocolate.AspNetCore.UploadedFile` to `HotChocolate.Types.IFile` 
This is where I got stuck a little, as `HotChocolate.AspNetCore.UploadedFile` inherits from `HotChocolate.Types.StreamFile` which does actually implement the `HotChocolate.Types.IFile` interface. So a conversion seems kinda strange to me? I must be missing something here, pretty sure.

**Comment by LukasDJacobs** [comment]
OK, got this fixed. Was really just one line.
Am I supposed to just open a new pull request and let you close this one or what's your process?

**Comment by tobias-tengler** [comment]
You can comment the line here and I'll include it. I'll be sure to credit you in thr merge commit :)

**Comment by LukasDJacobs** [comment]
DefaultTypeConverter.cs - Line 147 - old:
`if (source == target || target == typeof(object)`

DefaultTypeConverter.cs - Line 147 - new:
`if (target == typeof(object) || target.IsAssignableFrom(source))`

File: src/HotChocolate/Core/src/Types/Utilities/DefaultTypeConverter.cs [hunk 1]
```diff
@@ -144,7 +144,7 @@ private bool TryConvertInternal(Type from, Type to, object source, out object? c
             Type target,
             [NotNullWhen(true)] out ChangeType? converter)
         {
-            if (source == target || target == typeof(object))
+            if (target == typeof(object) || target.IsAssignableFrom(source))
```
Comment (tobias-tengler) [inline src/HotChocolate/Core/src/Types/Utilities/DefaultTypeConverter.cs:147]: @michaelstaib this fixes the issue at hand and the tests show no issues. Seems like it could have side-effects though. What are your thoughts on this change?

Comment (LukasDJacobs) [reply src/HotChocolate/Core/src/Types/Utilities/DefaultTypeConverter.cs:147]: Actually thought about this as well. IsAssignableFrom() includes ==, but also returns true if target inherits from source. From my experience and tests the performance is not an issue, but I see your point as it could potentially be something to cause issues further down the line.

**Comment by LukasDJacobs** [comment]
Any reason why this hasn't been reviewed yet?
Don't want to be annoying, but this is really causing some trouble for our project

**Comment by michaelstaib** [comment]
@LukasDJacobs was not yet tagged for review. Is it ready or still in progress?

**Comment by michaelstaib** [comment]
I have added it to the review backlog. It still will take me some time. I have a huge backlog at the moment and some team members are on vacation :)

File: src/HotChocolate/Core/src/Types/Utilities/DefaultTypeConverter.cs (hunk 1 above)
Comment (michaelstaib) [reply src/HotChocolate/Core/src/Types/Utilities/DefaultTypeConverter.cs:147]: I will write some performance tests for this one.
